spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}/${DB_AUTH_DATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${DB_AUTH_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

server:
  port: 8081
  servlet:
    session:
      cookie:
        name: AUTHSESSION

oauth2:
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.authentication: TRACE