services:
  database:
    image: postgres:17-alpine
    container_name: database
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${DB_AUTH_DATABASE}:${DB_AUTH_USERNAME}, ${DB_NOTIFICATION_DATABASE}:${DB_NOTIFICATION_USERNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./infra/script/db:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgres/data
    ports:
      - "5432:5432"

  cache:
    image: redis:8.2-alpine
    container_name: cache
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  broker:
    image: apache/kafka:4.1.1
    container_name: kafka-server
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3

volumes:
  redis-data:
  kafka-data:
  pg-data: