services:
  database:
    image: postgres:17-alpine
    container_name: database
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${DB_AUTH_DATABASE}:${DB_AUTH_USERNAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./infra/script/db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"

  cache:
    image: redis:8.2-alpine
    container_name: cache
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

volumes:
  redisdata:
  pgdata: